### ISSUE TITLE
Rename and restructure repository

### ISSUE THREAD

**Issue by hknutsen** [hknutsen/fedora-workstation#33]
This repository no longer contains only "utility scripts", but scripts, playbooks and documentation for everything I do on (and learn about) Fedora Workstation.

## Tasks

- [x] Rename repository to `fedora-workstation`.
- [x] Update README according to renaming.
- [x] Move all scripts into a new directory `scripts`.
- [x] Move all playbooks into a new directory `playbooks`.
- [x] Move all documentation into a new directory `docs`.
